<?php
/**
 * @poem.module
 */

/**
 * Implements hook_menu().
 */
function poem_menu() {
  $items = array();

  $items['poem'] = array(
    'title' => 'Poem',
    'page callback' => 'poem_page',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * @return $form
 *  Form array.
 * 
 * http://api.drupal.org/api/drupal/developer%21topics%21forms_api_reference.html/7
 */
function poem_form($form, &$form_state) {
  $form['roses'] = array(
    '#type' => 'radios',
    '#title' => t('Roses are...'),
    '#description' => t('Describe what color roses will be in your poem. Suggestion: Good poetry always rhymes.'),
    '#default_value' => variable_get('poem_roses', 'red'),
    '#options' => array(
      'red' => t('red'),
      'white' => t('white'),
    ),
  );
  $form['violets'] = array(
    '#type' => 'radios',
    '#title' => t('Roses are...'),
    '#description' => t('Describe what color roses will be in your poem. Suggestion: Good poetry always rhymes.'),
    '#default_value' => variable_get('poem_violets', 'blue'),
    '#options' => array(
      'blue' => t('blue'),
      'green' => t('green'),
    ),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Generate poem'),
  );

  return $form;
}

function poem_theme() {
  return array(
    'poem_prose' => array(
      'variables' => array('roses' => NULL, 'violets' => NULL, ),
      'template' => 'poem-prose'
    )
  );
}

function poem_page () {
  $form = drupal_get_form("poem_form");
  return $form;
}


/**
 * Validation handler for poem_form form.
 */
/*
// Uncomment this to implement validation handler here.
function poem_form_validate($form, &$form_state) {
}
// */

/**
 * Submit handler for poem_form form.
 */
function poem_form_submit($form, &$form_state) {
  $values = $form_state['values'];

  $roses = $values['roses'];
  variable_set('poem_roses', $roses);

  $violets = $values['violets'];
  variable_set('poem_violets', $violets);

  $text = theme('poem_prose', array('roses' => $roses, 'violets' => $violets));

  drupal_set_message($text);
}
